# Generated by Django 3.1.7 on 2021-03-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('image', models.ImageField(default='images/service/default.jpg', upload_to='images/service')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Predefined Order'), (2, 'Custom Order')], default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Processing'), (3, 'Delivered'), (4, 'Canceled')], default=1),
        ),
    ]
