# Generated by Django 3.1.7 on 2021-04-25 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20210425_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedservice',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 25, 15, 56, 54, 242006)),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='added_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 25, 15, 56, 54, 242006)),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 25, 15, 56, 54, 240013)),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 25, 15, 56, 54, 242006)),
        ),
    ]
