# Generated by Django 3.1.7 on 2021-05-10 05:07

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_auto_20210510_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 10, 10, 37, 43, 996710)),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='added_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 10, 10, 37, 43, 997708)),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 10, 10, 37, 43, 994717)),
        ),
        migrations.AlterField(
            model_name='quote',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 10, 10, 37, 43, 996710)),
        ),
    ]
