# Generated by Django 3.1.7 on 2021-05-12 06:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_auto_20210511_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 12, 11, 33, 41, 950291)),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='added_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 12, 11, 33, 41, 950291)),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 12, 11, 33, 41, 948296)),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 12, 11, 33, 41, 950291)),
        ),
    ]
