# Generated by Django 3.1.7 on 2021-05-12 12:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_auto_20210512_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='added_on',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='discount',
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 12, 17, 58, 8, 891761)),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 12, 17, 58, 8, 889767)),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 12, 17, 58, 8, 890762)),
        ),
    ]
