# Generated by Django 3.1.7 on 2021-05-26 06:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_auto_20210526_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 26, 11, 55, 4, 656699)),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 26, 11, 55, 4, 654697)),
        ),
        migrations.AlterField(
            model_name='order',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 26, 11, 55, 4, 656699)),
        ),
    ]
