# Generated by Django 3.1.7 on 2021-05-31 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_auto_20210530_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='raeted_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 31, 14, 19, 28, 870145)),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 31, 14, 19, 28, 872137)),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 31, 14, 19, 28, 870145)),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 31, 14, 19, 28, 872137)),
        ),
    ]
